# PPO Training Configuration for CartPole-v1
# This config demonstrates the full training pipeline with state-of-the-art settings

defaults:
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# Environment Configuration
env:
  name: "CartPole-v1"
  max_episode_steps: 500
  render_mode: null  # Disable rendering for training speed

# Model Architecture
model:
  actor:
    type: "mlp"
    hidden_sizes: [64, 64]
    activation: "tanh"
    std: 0.0  # Learnable std
  critic:
    type: "mlp" 
    hidden_sizes: [64, 64]
    activation: "tanh"

# PPO Algorithm Parameters
algorithm:
  name: "ppo"
  learning_rate: 3e-4
  n_steps: 2048
  batch_size: 64
  n_epochs: 10
  gamma: 0.99
  gae_lambda: 0.95
  clip_range: 0.2
  clip_range_vf: null
  normalize_advantage: true
  ent_coef: 0.0
  vf_coef: 0.5
  max_grad_norm: 0.5
  use_sde: false
  sde_sample_freq: -1
  target_kl: null

# Training Configuration
training:
  total_timesteps: 50000
  eval_freq: 1000
  n_eval_episodes: 10
  save_freq: 5000
  log_freq: 100
  
# Optimization
optimizer:
  type: "adamw"
  weight_decay: 1e-4
  eps: 1e-7
  amsgrad: false

# Compilation (PyTorch 2.3)
compilation:
  enabled: true
  mode: "reduce-overhead"
  fullgraph: true
  dynamic: false

# Logging
logging:
  wandb:
    enabled: true
    project: "tinyrl"
    entity: null
    tags: ["ppo", "cartpole", "v1.0"]
    group: "baseline"
  tensorboard: false
  csv: true

# Reproducibility
seed: 42
deterministic: true

# Output Configuration
output:
  dir: "./outputs/ppo_cartpole"
  save_model: true
  save_replay_buffer: false
  save_vecnormalize: true

# Callbacks
callbacks:
  - _target_: tinyrl.callbacks.WandbCallback
    verbose: 1
  - _target_: tinyrl.callbacks.EvalCallback
    eval_env: null  # Will be created automatically
    best_model_save_path: null  # Will be set automatically
    log_path: null  # Will be set automatically
    eval_freq: 1000
    deterministic: true
    render: false
  - _target_: tinyrl.callbacks.CheckpointCallback
    save_freq: 5000
    save_path: null  # Will be set automatically
    name_prefix: "ppo_model" 